KanBan v2.3
Yasovik/java-kanban pull request #2
Opened 2024-12-17 21:20 UTC by Yasovik

Финальное задание 7го спринта:
Добавлено запись/чтение задач из файла.

Добавлены тесты на новую функциональность запись/чтение

2024-12-18 16:22 UTC, Fleaman777 requested changes

2024-12-18 16:22 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +    private String taskToString(Task task) {
private методы должны идти после публичных, так при беглом просмотре класса, можно будет быстро понять, какой функционал он отдает наружу

2024-12-18 16:22 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +    }
эти 3 метода похожи между собой, можно подумать над тем, что бы общую часть вынести в общий метод

2024-12-18 16:22 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +    private static Task fromString(String value) {
этот метод не должен быть static

2024-12-18 16:22 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +            task = new Subtask(parts[2], parts[4], Status.valueOf(parts[3]), Integer.parseInt(parts[5]));
хорошо было бы значения из массива вынести в локальные переменные, так код будет чище и понятней

2024-12-18 16:22 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +    }
не хватает переобпределение метода, который удаляет все задачи всех типов

2024-12-18 16:22 UTC, Fleaman777 commented on test/manager/FileBackedTaskManagerTest.java
> +        fileBackedTaskManager.save();
этот метод не должен вызываться напрямую, так как он уже вызывается в addTask

2024-12-18 18:59 UTC, Yasovik commented on src/manager/FileBackedTaskManager.java
> +    private String taskToString(Task task) {
Исправлено

2024-12-18 19:01 UTC, Yasovik commented on src/manager/FileBackedTaskManager.java
> +    private static Task fromString(String value) {
Исправлено

2024-12-18 19:07 UTC, Yasovik commented on test/manager/FileBackedTaskManagerTest.java
> +        fileBackedTaskManager.save();
Исправлено

2024-12-18 19:17 UTC, Yasovik commented on src/manager/FileBackedTaskManager.java
> +    }
Исправлено

2024-12-18 20:24 UTC, Yasovik commented on src/manager/FileBackedTaskManager.java
> +    }
Исправлено

2024-12-19 07:32 UTC, Yasovik commented on src/manager/FileBackedTaskManager.java
> +            task = new Subtask(parts[2], parts[4], Status.valueOf(parts[3]), Integer.parseInt(parts[5]));
Исправлено

2024-12-19 21:04 UTC, Fleaman777 approved these changes

2024-12-19 21:04 UTC, Fleaman777 commented on src/manager/FileBackedTaskManager.java
> +    }
отлично, то, что нужно

2025-01-11 09:24 UTC, merged